pos/delivery/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'delivery'
urlpatterns = [
    path('test',views.test, name='test'),
    ]

pos/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
    path('test',views.test, name='test'),
    path('HomeView', HomeView.as_view(), name='HomeView'),
    path('ProductCreate', ProductCreate.as_view(), name='ProductCreate'),
    path('ProductEditView/<int:pk>/', ProductEditView.as_view(), name='ProductEditView'),
    path('CategoryCreate',CategoryCreate.as_view(), name='CategoryCreate'),
    path('ProductColorSetup/<int:pk>/', ProductColorSetup.as_view(), name='ProductColorSetup'),
    path('ProductColorSave/', ProductColorSave.as_view(), name='ProductColorSave'),
    path('ProductSizeSave/', ProductSizeSave.as_view(), name='ProductSizeSave'),
    path('login', UserLoginView.as_view(), name = 'UserLoginView'),
    path('logout/', UserLogoutView.as_view(), name='UserLogoutView'),
    path('AddToCartView/<int:pro_id>', AddToCartView.as_view(), name='AddToCartView'),
    path('mycart/', MyCartView.as_view(), name='MyCartView'),
    path('manage/<int:cp_id>/', ManageCartView.as_view(), name='ManageCartView'),
    path('checkout/', CheckoutView.as_view(), name='CheckoutView'),
    path('empty/', EmptyCartView.as_view(), name='EmptyCartView'),

    path('SupplierCreate/', SupplierCreate.as_view(), name='SupplierCreate'),
    path('SupplierEdit/<int:pk>/', SupplierEdit.as_view(), name='SupplierEdit'),
    path('PurchaseCreateView/<int:id>/', PurchaseCreateView.as_view(), name='PurchaseCreateView'),
    path('PurchaseData/', PurchaseData.as_view(), name='PurchaseData'),
    path('PurchaseReport/', PurchaseReport.as_view(), name='PurchaseReport'),
    path('PurchaseDataDelete/<int:pk>/', PurchaseDataDelete.as_view(), name='PurchaseDataDelete'),

    path('SaleInvoiceView/', SaleInvoiceView.as_view(), name='SaleInvoiceView'),
    path('SaleInvoiceReportFilter/', SaleInvoiceReportFilter.as_view(), name='SaleInvoiceReportFilter'),
    path('InvoiceDetailView/<int:pk>/', InvoiceDetailView.as_view(), name='InvoiceDetailView'),
    path('InvoiceStatusChange/<int:pk>/', InvoiceStatusChange.as_view(), name='InvoiceStatusChange'),
    path('SaleItemReportView', SaleItemReportView.as_view(), name='SaleItemReportView'),
    path('GPView', GPView.as_view(), name='GPView'),
    path('Deliverpayment/<int:pk>', Deliverpayment.as_view(), name='Deliverpayment'),
    path('DeliveryPaymentReportView/', DeliveryPaymentReportView, name='DeliveryPaymentReportView'),
    path('InvoiceThermalPrintView/<int:pk>/', InvoiceThermalPrintView.as_view(), name='InvoiceThermalPrintView'),

    path('DamageItemView/', DamageItemView.as_view(), name='DamageItemView'),
    path('DamageInvoiceView/<int:id>/', DamageInvoiceView.as_view(), name='DamageInvoiceView'),
    path('DamageProductView/<int:id>/', DamageProductView.as_view(), name='DamageProductView'),
    path('DamageReportView/', DamageReportView.as_view(), name='DamageReportView'),

    path('ExpenseLedgerView/<int:id>', ExpenseLedgerView.as_view(), name='ExpenseLedgerView'),
    path('LedgerImport/', LedgerImport.as_view(), name='LedgerImport'),
    path('ExpenseReportView/', ExpenseReportView.as_view(), name='ExpenseReportView'),
    path('ExpenseReportFilter/', ExpenseReportFilter.as_view(), name='ExpenseReportFilter'),
    path('LedgerCreateView/', LedgerCreateView.as_view(), name='LedgerCreateView'),

    path('Dashboard/', DashboardView.as_view(), name='DashboardView'),
    # path('DashboardReportView/', DashboardReportView, name='DashboardReportView'),
    path('testbarcode/', testbarcode.as_view(), name='testbarcode'),
    path('DeliveryView', DeliveryView.as_view(), name= 'DeliveryView'),
    path('pdf_invoice_create/<int:id>/', pdf_invoice_create, name='pdf_invoice_create'),
    path('second_dashboard', views.second_dashboard, name='second_dashboard' ),
    path('EcommerceSaleOrder/', EcommerceSaleOrder.as_view(), name='EcommerceSaleOrder'),

#V2
    path('POSView/', POSView.as_view(), name='POSView'),
    path('get-items-by-category/', GetItemsByCategory.as_view(), name='GetItemsByCategory'),
    path('report2/', Report2.as_view(), name='Report2'),
    path('getReport/', getReport.as_view(), name='getReport'),
    path('DeleteReport/', DeleteReport.as_view(), name='DeleteReport'),


#website section
    path('', webpage_home.as_view(), name='webpage_home'),
    path('pro_detail/<int:id>/', pro_detail.as_view(), name='pro_detail'),
    path('WebsiteAddtoCart/<int:pro_id>', WebsiteAddtoCart.as_view(), name='WebsiteAddtoCart'),
    path('WebAddtoCart/', WebAddtoCart.as_view(), name='WebAddtoCart'),
    path('WebItemDetailOrder/', WebItemDetailOrder.as_view(), name='WebItemDetailOrder'),
    path('WebCartView/', WebCartView.as_view(), name='WebCartView'),
    path('WebCartManage/<int:cp_id>/', WebCartManage.as_view(), name='WebCartManage'),
    path('WebCheckOut/', WebCheckOut.as_view(), name='WebCheckOut'),
    path('EcommerceBanner/', EcommerceBannerView.as_view(), name='EcommerceBanner'),
    path('EcommerceCheckoutOrder/', EcommerceCheckoutOrder.as_view(), name='EcommerceCheckoutOrder'),
    path('NotiOrderDetailView/<int:eid>/', NotiOrderDetailView.as_view(), name='NotiOrderDetailView'),
    path('ContactUsView/', ContactUsView.as_view(), name='ContactUsView'),
    path('BestSeller/', BestSeller.as_view(), name='BestSeller'),
    path('NewArrival/', NewArrival.as_view(), name='NewArrival'),
    path('NewArrivalSetup/', NewArrivalSetup.as_view(), name='NewArrivalSetup'),
    path('NewArrivalRemove/<int:pk>/', NewArrivalRemove.as_view(), name='NewArrivalRemove'),
    path('BestSellerSetup/', BestSellerSetup.as_view(), name='BestSellerSetup'),
    path('BestSellerItemEdit/<int:pk>/', BestSellerItemEdit.as_view(), name='BestSellerItemEdit'),
#message    
    path('messageaddview/', messageaddview.as_view(), name='messageaddview'),
    path('AdminMessageView/', AdminMessageView.as_view(), name='AdminMessageView'),
    path('AdminMessageItemFilter/', AdminMessageItemFilter, name='AdminMessageItemFilter'),
    path('adminmessagereply/',  adminmessagereply.as_view(), name='adminmessagereply'),



]

pos/pos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('delivery/', include('delivery.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/delivery/models.py
from django.db import models

# Create your models here.

pos/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name

class Supplier(models.Model):
    supplier_name = models.CharField(max_length=225)
    phone_number = models.CharField(max_length=225)
    address = models.CharField(max_length=225)

    def __del__(self):
        return self.supplier_name

class Category(models.Model):
    category_name = models.CharField(max_length=225)

    def __str__(self):
        return self.category_name

class Items(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    pruchase_price = models.FloatField(default=0.00)
    sell_price = models.FloatField(default=0.00)
    balance_qty = models.IntegerField(default=0)
    barcode_id = models.CharField(max_length=225,blank=True, null=True)
    photo = models.ImageField(upload_to='', blank=True, null=True)
    photo2 = models.ImageField(upload_to='', blank=True, null=True)
    photo3 = models.ImageField(upload_to='', blank=True, null=True)
    photo4 = models.ImageField(upload_to='', blank=True, null=True)
    itm_description = models.CharField(max_length=225,blank=True, null=True)

    def __str__(self):
        return self.item_name

class ItmColor(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    color = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color

class ItmSize(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    size = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.size

class Cart(models.Model):
    staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    super_total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    color = models.CharField(max_length=255,null=True, blank=True)
    size = models.CharField(max_length=255,null=True, blank=True)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    remain_balance = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Cart : "+ str(self.cart.id)+ "CartProduct : " + str(self.id)

STATUS=(
    ("Ordering","Ordering"),("Delivered","Delivered"),("Cash","Cash"),("Credit","Credit"),("Consignment","Consignment"),("Complete","Complete")
)

PAYMENT_TYPE = (
    ("Cash","Cash"),
("COD","COD"),
("Kpay","Kpay"),
("WavePay","WavePay"),
)

class DeliverySystem(models.Model):
    delivery_name = models.CharField(max_length=225)

    def __str__(self):
        return self.delivery_name

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=255,null=True, blank=True)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255,null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    delivery_fee = models.IntegerField(default=0)
    delivery_system = models.ForeignKey(DeliverySystem, on_delete=models.CASCADE, blank=True,null=True)
    all_total = models.PositiveIntegerField()
    all_total_delivery = models.IntegerField(default=0)
    ordered_staus = models.CharField(max_length=255, choices=STATUS, default='Cash')
    payment = models.CharField(max_length=225, choices=PAYMENT_TYPE, default='Cash')
    deli_payment = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Order : " + str(self.id)


class PurchaseList(models.Model):
    supplier_name = models.CharField(max_length=225)
    item_name = models.CharField(max_length=225)
    purchase_qty = models.IntegerField(default=0)
    purchase_price = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    logistic = models.IntegerField(default=0)
    total_purchase_price = models.IntegerField(default=0)
    p_date = models.DateField()
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.item_name

class DamageItems(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225,blank=True,null=True)
    item_code = models.CharField(max_length=225,blank=True,null=True)
    quantity = models.IntegerField(default=0)
    description = models.CharField(max_length=225,blank=True,null=True)
    return_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)

class ExpenseLedger(models.Model):
    category = models.CharField(max_length=225,unique=True)
    balance = models.IntegerField(default=0)

class ExpenseReport(models.Model):
    expense_type = models.CharField(max_length=225)
    title = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    amount = models.IntegerField(default=0)
    expense_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)




#website


class EcommerceBanner(models.Model):
    photo1 = models.ImageField(upload_to='', blank=True, null=True)
    photo2 = models.ImageField(upload_to='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class EcommerceCart(models.Model):
    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    super_total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class EcommerceCartProduct(models.Model):
    cart = models.ForeignKey(EcommerceCart, on_delete=models.CASCADE)
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    item_color = models.CharField(max_length=255,null=True, blank=True)
    item_size = models.CharField(max_length=255,null=True, blank=True)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    remain_balance = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Cart : "+ str(self.cart.id)+ "CartProduct : " + str(self.id)

class EcommerceOrder(models.Model):
    cart = models.OneToOneField(EcommerceCart, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=255,null=True, blank=True)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255,null=True, blank=True)
    orderstatus = models.PositiveIntegerField(default=1)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Order : " + str(self.id)


class BestSellers(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class NewArrival(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class newestitem(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

############ Messenger Bot ################################
class messengerid(models.Model):
    m_status = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return str(self.id)


class messengerbot(models.Model):
    messengerid = models.ForeignKey(messengerid, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    status_id = models.PositiveIntegerField(default=1)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pos/delivery/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def test(request):
    return HttpResponse('Hello Test')

pos/templates/invoice_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Helll PDF</h1>
</body>
</html>

pos/templates/productcreate.html
{% extends 'base.html' %}

{% block content %}

<!--<div class="page-header">-->
<!--    <div class="row">-->
<!--        <div class="col-md-6 col-sm-12">-->
<!--            <div class="title">-->
<!--                <h5>Create New Product</h5>-->

<!--            </div>-->
<!--            <hr>-->
<!--            {% if message %}-->
<!--            <div class="alert alert-danger" role="alert">-->
<!--                {{message}}-->
<!--            </div>-->
<!--            {% endif %}-->
<!--        </div>-->
<!--    </div>-->
<!--    <div class="row">-->
<!--        <div class="col-md-6 col-sm-12">-->
<!--            <form action="{% url 'myapp:ProductCreate' %}" method="post">{% csrf_token %}-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Item Name</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="text" placeholder="" name="item_name">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Category</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <select class="custom-select col-12" name="category">-->
<!--                            <option selected="">Select Category Name</option>-->
<!--                            {% for c in category %}-->
<!--                            <option>{{c.category_name}}</option>-->
<!--                            {% endfor %}-->

<!--                        </select>-->
<!--                    </div>-->

<!--                </div>-->

<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Purchase Price</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" name="purchase_price">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">Sale Price</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" name="sale_price">-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="form-group row">-->
<!--                    <label class="col-sm-12 col-md-2 col-form-label">BarCode</label>-->
<!--                    <div class="col-sm-12 col-md-10">-->
<!--                        <input class="form-control" type="number" placeholder="" value="0" name="barcode_id">-->
<!--                    </div>-->
<!--                </div>-->


<!--                <input type="submit" value="CreateProduct" class="btn btn-outline-primary">-->


<!--            </form>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

{% if message %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endif %}


<h4 class="text-blue h4">Item List</h4>
<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
<!--        <h4 class="text-blue h4">Item List</h4>-->
        <a
									href="#"
									class="btn btn-sm btn-outline-primary"
									data-toggle="modal"
									data-target="#Medium-modal"
									type="button"
								>
									+ Add Item Name
								</a>
								<div
									class="modal fade"
									id="Medium-modal"
									tabindex="-1"
									role="dialog"
									aria-labelledby="myLargeModalLabel"
									aria-hidden="true"
								>
									<div class="modal-dialog modal-dialog-centered">
                                        <form action="{% url 'myapp:ProductCreate' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
										<div class="modal-content">
											<div class="modal-header">
												<h4 class="modal-title" id="myLargeModalLabel">
													New Item
												</h4>
												<button
													type="button"
													class="close"
													data-dismiss="modal"
													aria-hidden="true"
												>
													×
												</button>
											</div>

											<div class="modal-body">
												<div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Item Name</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="item_name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Category</label>
                    <div class="col-sm-12 col-md-10">
                        <select class="custom-select col-12" name="category">
                            <option selected="">Select Category Name</option>
                            {% for c in category %}
                            <option>{{c.category_name}}</option>
                            {% endfor %}

                        </select>
                    </div>

                </div>

                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Purchase Price</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="number" placeholder="" name="purchase_price">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Sale Price</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="number" placeholder="" name="sale_price">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">BarCode</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" value="0" name="barcode_id">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Description</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" value="How To" name="itmdesc">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Photo1[800x800]</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="file" placeholder="" value="0" name="photo">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Photo2[800x800]</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="file" placeholder="" value="0" name="photo2">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Photo3[800x800]</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="file" placeholder="" value="0" name="photo3">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-12 col-form-label">Photo4[800x800]</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="file" placeholder="" value="0" name="photo4">
                    </div>
                </div>
											</div>
											<div class="modal-footer">
												<button
													type="button"
													class="btn btn-secondary"
													data-dismiss="modal"
												>
													Close
												</button>
												<button type="submit" class="btn btn-primary">
													Save Item Name
												</button>
											</div>
										</div>
                                            </form>
									</div>
								</div>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-warning">

                <th>Name</th>
                <th>Category</th>
                <th>PurchasePrice</th>
                <th>SalePrice</th>
                <th>BalanceQTY</th>
                <th>Color & Size</th>

            </tr>
            </thead>
            <tbody>
            {% for p in item_list %}
            <tr>
                <td class="table-plus"><a href="{% url 'myapp:ProductEditView' p.id %}"><b>{{p.item_name}}</b></a></td>
                <td>{{p.category}}</td>
                <td>{{p.pruchase_price}}</td>
                <td>{{p.sell_price}}</td>
                <td>{{p.balance_qty}}</td>
                <td>
                    <a href="{% url 'myapp:ProductColorSetup' p.id%}" type="submit"><span class="badge badge-info badge-pill">Add Color & Size</span></a>
                    
                </td>


            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}

pos/templates/statuschange.html
{% extends 'base.html' %}

{% block content %}
<!--filter form-->
<div class="pd-20 card-box mb-30">
    <div class="clearfix">
        <div class="pull-left">

        </div>
    </div>
    <form action="" method="post">{% csrf_token %}
        <div class="row">

            {{form}}
<button
                type="submit"
                class="btn btn-sm"
                data-bgcolor="#00b489"
                data-color="#ffffff"
        >
            Change Status

        </button>

        </div>

        <div>
            {% if message %}
            <hr>
        <a href="{{current_path}}" class="text-danger">{{message}}</a>
        {% endif %}
        </div>


    </form>
</div>


{% endblock content %}

pos/templates/supplier.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="title">
                <h5>Create New Supplier</h5>

            </div>
            <hr>
            {% if message %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% endif %}
            {% if success %}
            <div class="alert alert-success" role="alert">
                {{success}}
            </div>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 col-sm-12">
            <form action="{% url 'myapp:SupplierCreate' %}" method="post">{% csrf_token %}
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Supplier Name</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="supplier_name">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Phone Number</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="phone_number">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="col-sm-12 col-md-2 col-form-label">Address</label>
                    <div class="col-sm-12 col-md-10">
                        <input class="form-control" type="text" placeholder="" name="address">
                    </div>
                </div>


                <input type="submit" value="Create Supplier" class="btn btn-outline-primary">


            </form>
        </div>
    </div>
</div>


<!--=============================================================-->
<div class="card-box mb-30">
    <div class="pd-20">
        <h4 class="text-blue h4">Supplier List</h4>

    </div>
    <div class="pb-20">
        <table class="data-table table stripe hover nowrap">
            <thead>
            <tr class="table-warning">

                <th class="text-center">Supplier Name</th>
                <th class="text-center">Phone Number</th>
                <th class="text-center">Address</th>
<!--                <th>Vou</th>-->


            </tr>
            </thead>
            <tbody>
            {% for p in supplier %}
            <tr class="table-info">
                <td class="table-plus text-center"><a href="{% url 'myapp:SupplierEdit' p.id %}"><b>{{p.supplier_name}}</b></a></td>
                <td>{{p.phone_number}}</td>
                <td>{{p.address}}</td>
<!--                <td><a href="{% url 'myapp:PurchaseCreateView' p.id%}">Vouch</a></td>-->

            </tr>
            {% endfor %}

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}