pos/myapp/urls.py
from django.urls import path
from .views import *
from . import views
app_name = 'myapp'
urlpatterns = [
    path('test',views.test, name='test'),
    path('HomeView', HomeView.as_view(), name='HomeView'),
    path('ProductCreate', ProductCreate.as_view(), name='ProductCreate'),
    path('ProductEditView/<int:pk>/', ProductEditView.as_view(), name='ProductEditView'),
    path('CategoryCreate',CategoryCreate.as_view(), name='CategoryCreate'),
    path('ProductColorSetup/<int:pk>/', ProductColorSetup.as_view(), name='ProductColorSetup'),
    path('ProductColorSave/', ProductColorSave.as_view(), name='ProductColorSave'),
    path('ProductSizeSave/', ProductSizeSave.as_view(), name='ProductSizeSave'),
    path('login', UserLoginView.as_view(), name = 'UserLoginView'),
    path('logout/', UserLogoutView.as_view(), name='UserLogoutView'),
    path('AddToCartView/<int:pro_id>', AddToCartView.as_view(), name='AddToCartView'),
    path('mycart/', MyCartView.as_view(), name='MyCartView'),
    path('manage/<int:cp_id>/', ManageCartView.as_view(), name='ManageCartView'),
    path('checkout/', CheckoutView.as_view(), name='CheckoutView'),
    path('empty/', EmptyCartView.as_view(), name='EmptyCartView'),

    path('SupplierCreate/', SupplierCreate.as_view(), name='SupplierCreate'),
    path('SupplierEdit/<int:pk>/', SupplierEdit.as_view(), name='SupplierEdit'),
    path('PurchaseCreateView/<int:id>/', PurchaseCreateView.as_view(), name='PurchaseCreateView'),
    path('PurchaseData/', PurchaseData.as_view(), name='PurchaseData'),
    path('PurchaseReport/', PurchaseReport.as_view(), name='PurchaseReport'),
    path('PurchaseDataDelete/<int:pk>/', PurchaseDataDelete.as_view(), name='PurchaseDataDelete'),

    path('SaleInvoiceView/', SaleInvoiceView.as_view(), name='SaleInvoiceView'),
    path('SaleInvoiceReportFilter/', SaleInvoiceReportFilter.as_view(), name='SaleInvoiceReportFilter'),
    path('InvoiceDetailView/<int:pk>/', InvoiceDetailView.as_view(), name='InvoiceDetailView'),
    path('InvoiceStatusChange/<int:pk>/', InvoiceStatusChange.as_view(), name='InvoiceStatusChange'),
    path('SaleItemReportView', SaleItemReportView.as_view(), name='SaleItemReportView'),
    path('GPView', GPView.as_view(), name='GPView'),
    path('Deliverpayment/<int:pk>', Deliverpayment.as_view(), name='Deliverpayment'),
    path('DeliveryPaymentReportView/', DeliveryPaymentReportView, name='DeliveryPaymentReportView'),
    path('InvoiceThermalPrintView/<int:pk>/', InvoiceThermalPrintView.as_view(), name='InvoiceThermalPrintView'),

    path('DamageItemView/', DamageItemView.as_view(), name='DamageItemView'),
    path('DamageInvoiceView/<int:id>/', DamageInvoiceView.as_view(), name='DamageInvoiceView'),
    path('DamageProductView/<int:id>/', DamageProductView.as_view(), name='DamageProductView'),
    path('DamageReportView/', DamageReportView.as_view(), name='DamageReportView'),

    path('ExpenseLedgerView/<int:id>', ExpenseLedgerView.as_view(), name='ExpenseLedgerView'),
    path('LedgerImport/', LedgerImport.as_view(), name='LedgerImport'),
    path('ExpenseReportView/', ExpenseReportView.as_view(), name='ExpenseReportView'),
    path('ExpenseReportFilter/', ExpenseReportFilter.as_view(), name='ExpenseReportFilter'),
    path('LedgerCreateView/', LedgerCreateView.as_view(), name='LedgerCreateView'),

    path('Dashboard/', DashboardView.as_view(), name='DashboardView'),
    # path('DashboardReportView/', DashboardReportView, name='DashboardReportView'),
    path('testbarcode/', testbarcode.as_view(), name='testbarcode'),
    path('DeliveryView', DeliveryView.as_view(), name= 'DeliveryView'),
    path('pdf_invoice_create/<int:id>/', pdf_invoice_create, name='pdf_invoice_create'),
    path('second_dashboard', views.second_dashboard, name='second_dashboard' ),
    path('EcommerceSaleOrder/', EcommerceSaleOrder.as_view(), name='EcommerceSaleOrder'),

#V2
    path('POSView/', POSView.as_view(), name='POSView'),
    path('get-items-by-category/', GetItemsByCategory.as_view(), name='GetItemsByCategory'),
    path('report2/', Report2.as_view(), name='Report2'),
    path('getReport/', getReport.as_view(), name='getReport'),
    path('DeleteReport/', DeleteReport.as_view(), name='DeleteReport'),


#website section
    path('', webpage_home.as_view(), name='webpage_home'),
    path('pro_detail/<int:id>/', pro_detail.as_view(), name='pro_detail'),
    path('WebsiteAddtoCart/<int:pro_id>', WebsiteAddtoCart.as_view(), name='WebsiteAddtoCart'),
    path('WebAddtoCart/', WebAddtoCart.as_view(), name='WebAddtoCart'),
    path('WebItemDetailOrder/', WebItemDetailOrder.as_view(), name='WebItemDetailOrder'),
    path('WebCartView/', WebCartView.as_view(), name='WebCartView'),
    path('WebCartManage/<int:cp_id>/', WebCartManage.as_view(), name='WebCartManage'),
    path('WebCheckOut/', WebCheckOut.as_view(), name='WebCheckOut'),
    path('EcommerceBanner/', EcommerceBannerView.as_view(), name='EcommerceBanner'),
    path('EcommerceCheckoutOrder/', EcommerceCheckoutOrder.as_view(), name='EcommerceCheckoutOrder'),
    path('NotiOrderDetailView/<int:eid>/', NotiOrderDetailView.as_view(), name='NotiOrderDetailView'),
    path('ContactUsView/', ContactUsView.as_view(), name='ContactUsView'),
    path('BestSeller/', BestSeller.as_view(), name='BestSeller'),
    path('NewArrival/', NewArrival.as_view(), name='NewArrival'),
    path('NewArrivalSetup/', NewArrivalSetup.as_view(), name='NewArrivalSetup'),
    path('NewArrivalRemove/<int:pk>/', NewArrivalRemove.as_view(), name='NewArrivalRemove'),
    path('BestSellerSetup/', BestSellerSetup.as_view(), name='BestSellerSetup'),
    path('BestSellerItemEdit/<int:pk>/', BestSellerItemEdit.as_view(), name='BestSellerItemEdit'),
#message    
    path('messageaddview/', messageaddview.as_view(), name='messageaddview'),
    path('AdminMessageView/', AdminMessageView.as_view(), name='AdminMessageView'),
    path('AdminMessageItemFilter/', AdminMessageItemFilter, name='AdminMessageItemFilter'),
    path('adminmessagereply/',  adminmessagereply.as_view(), name='adminmessagereply'),



]

pos/pos/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('delivery/', include('delivery.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pos/myapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Test(models.Model):
    name = models.CharField(max_length=225)

    def __str__(self):
        return self.name

class Supplier(models.Model):
    supplier_name = models.CharField(max_length=225)
    phone_number = models.CharField(max_length=225)
    address = models.CharField(max_length=225)

    def __del__(self):
        return self.supplier_name

class Category(models.Model):
    category_name = models.CharField(max_length=225)

    def __str__(self):
        return self.category_name

class Items(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    pruchase_price = models.FloatField(default=0.00)
    sell_price = models.FloatField(default=0.00)
    balance_qty = models.IntegerField(default=0)
    barcode_id = models.CharField(max_length=225,blank=True, null=True)
    photo = models.ImageField(upload_to='', blank=True, null=True)
    photo2 = models.ImageField(upload_to='', blank=True, null=True)
    photo3 = models.ImageField(upload_to='', blank=True, null=True)
    photo4 = models.ImageField(upload_to='', blank=True, null=True)
    itm_description = models.CharField(max_length=225,blank=True, null=True)

    def __str__(self):
        return self.item_name

class ItmColor(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    color = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.color

class ItmSize(models.Model):
    items = models.ForeignKey(Items, on_delete=models.CASCADE)
    size = models.CharField(max_length=255,null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.size

class Cart(models.Model):
    staff = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    super_total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    color = models.CharField(max_length=255,null=True, blank=True)
    size = models.CharField(max_length=255,null=True, blank=True)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    remain_balance = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Cart : "+ str(self.cart.id)+ "CartProduct : " + str(self.id)

STATUS=(
    ("Ordering","Ordering"),("Delivered","Delivered"),("Cash","Cash"),("Credit","Credit"),("Consignment","Consignment"),("Complete","Complete")
)

PAYMENT_TYPE = (
    ("Cash","Cash"),
("COD","COD"),
("Kpay","Kpay"),
("WavePay","WavePay"),
)

class DeliverySystem(models.Model):
    delivery_name = models.CharField(max_length=225)

    def __str__(self):
        return self.delivery_name

class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=255,null=True, blank=True)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255,null=True, blank=True)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField(default=0)
    total = models.PositiveIntegerField()
    tax = models.PositiveIntegerField()
    delivery_fee = models.IntegerField(default=0)
    delivery_system = models.ForeignKey(DeliverySystem, on_delete=models.CASCADE, blank=True,null=True)
    all_total = models.PositiveIntegerField()
    all_total_delivery = models.IntegerField(default=0)
    ordered_staus = models.CharField(max_length=255, choices=STATUS, default='Cash')
    payment = models.CharField(max_length=225, choices=PAYMENT_TYPE, default='Cash')
    deli_payment = models.BooleanField(default=False)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Order : " + str(self.id)


class PurchaseList(models.Model):
    supplier_name = models.CharField(max_length=225)
    item_name = models.CharField(max_length=225)
    purchase_qty = models.IntegerField(default=0)
    purchase_price = models.IntegerField(default=0)
    sale_price = models.IntegerField(default=0)
    logistic = models.IntegerField(default=0)
    total_purchase_price = models.IntegerField(default=0)
    p_date = models.DateField()
    created_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.item_name

class DamageItems(models.Model):
    item_name = models.CharField(max_length=225)
    category = models.CharField(max_length=225,blank=True,null=True)
    item_code = models.CharField(max_length=225,blank=True,null=True)
    quantity = models.IntegerField(default=0)
    description = models.CharField(max_length=225,blank=True,null=True)
    return_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)

class ExpenseLedger(models.Model):
    category = models.CharField(max_length=225,unique=True)
    balance = models.IntegerField(default=0)

class ExpenseReport(models.Model):
    expense_type = models.CharField(max_length=225)
    title = models.CharField(max_length=225)
    category = models.CharField(max_length=225)
    amount = models.IntegerField(default=0)
    expense_date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)




#website


class EcommerceBanner(models.Model):
    photo1 = models.ImageField(upload_to='', blank=True, null=True)
    photo2 = models.ImageField(upload_to='', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class EcommerceCart(models.Model):
    total = models.PositiveIntegerField(default=0)
    tax = models.PositiveIntegerField(default=0)
    super_total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)


class EcommerceCartProduct(models.Model):
    cart = models.ForeignKey(EcommerceCart, on_delete=models.CASCADE)
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    item_color = models.CharField(max_length=255,null=True, blank=True)
    item_size = models.CharField(max_length=255,null=True, blank=True)
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()
    remain_balance = models.IntegerField()
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Cart : "+ str(self.cart.id)+ "CartProduct : " + str(self.id)

class EcommerceOrder(models.Model):
    cart = models.OneToOneField(EcommerceCart, on_delete=models.CASCADE)
    customer_name = models.CharField(max_length=255,null=True, blank=True)
    shipping_address = models.CharField(max_length=255, null=True, blank=True)
    mobile = models.CharField(max_length=255,null=True, blank=True)
    orderstatus = models.PositiveIntegerField(default=1)
    created_at = models.DateField(auto_now_add=True)

    def __str__(self):
        return "Order : " + str(self.id)


class BestSellers(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    rank = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class NewArrival(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class newestitem(models.Model):
    product = models.ForeignKey(Items, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

############ Messenger Bot ################################
class messengerid(models.Model):
    m_status = models.PositiveIntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # def __str__(self):
    #     return str(self.id)


class messengerbot(models.Model):
    messengerid = models.ForeignKey(messengerid, on_delete=models.CASCADE)
    message = models.CharField(max_length=255)
    status_id = models.PositiveIntegerField(default=1)
    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pos/templates/web/BestSeller.html
{% extends 'web/webbase.html' %}
{% load static %}

{% block content %}

    <!--Body Content-->
    <div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Best Seller Items in BESTBUY</h1></div>
      		</div>
		</div>
        <!--End Page Title-->

        <div class="container">
            <div class="row">

                <!--Main Content-->
                <div class="col-12 col-sm-12 col-md-12 col-lg-12 main-col">
                	<div class="category-description">
                    </div>
                    <hr>
                	<div class="productList">
                        <div class="grid-products grid--view-items">
                            <div class="row">
                               {% for i in bs %}
                                <div class="col-6 col-sm-6 col-md-4 col-lg-4 item">
                                    <!-- start product image -->
                                    <div class="product-image">
                                        <!-- start product image -->
                                        <a href="{% url 'myapp:pro_detail' i.product.id %}">
                                            <!-- image -->
                                            <img class="primary blur-up lazyload" data-src="{{i.product.photo.url}}" src="{{i.product.photo.url}}" alt="image" title="product">
                                            <!-- End image -->
                                            <!-- Hover image -->
                                            <img class="hover blur-up lazyload" data-src="{{i.product.photo2.url}}" src="{{i.product.photo2.url}}" alt="image" title="product">
                                            <!-- End hover image -->
                                            <!-- product label -->
                                            <div class="product-labels rounded"></div>
                                            <!-- End product label  lbl pr-label2 rounded-->
                                        </a>
                                        <!-- end product image -->

                                        <!-- Start product button -->
                                        <form class="variants add" action="{% url "myapp:pro_detail" i.product.id %}" onclick="window.location.href='{% url "myapp:pro_detail" i.product.id %}'" method="post">
                                            <button class="btn btn-addto-cart" type="button">See More Details</button>
                                        </form>

                                        <!-- end product button -->
                                    </div>
                                    <!-- end product image -->

                                    <!--start product details -->
                                    <div class="product-details text-center">
                                        <!-- product name -->
                                        <div class="product-name">
                                            <a href="#">{{i.product.item_name}}</a>
                                        </div>
                                        <!-- End product name -->
                                        <!-- product price -->
                                        <div class="product-price">
                                            <span class="price">{{i.product.sell_price}} MMK</span>
                                        </div>
                                        <!-- End product price -->


                                    </div>
                                    <!-- End product details -->
                                </div>
                                {% endfor %}


                            </div>
                        </div>
                    </div>
                </div>
                <!--End Main Content-->

            </div>
        </div>

    </div>
    <!--End Body Content-->


{% endblock content %}

pos/templates/web/EcommerceBanner.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<!--=============================================================-->


<div class="gallery-wrap">
    {% for i in p %}
    <ul class="row">
        <li class="col-lg-4 col-md-6 col-sm-12">
            <div class="da-card box-shadow">
                <div class="da-card-photo">
                    <img src="{{i.photo1.url}}" alt=""/>
                    <div class="da-overlay">
                        <div class="da-social">
                            <h5 class="mb-10 color-white pd-20">
                                1904x600
                            </h5>
                            <ul class="clearfix">

                                <li> </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal1">edit</button>
            <div class="modal fade" id="myModal1" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                        </div>
                        <div class="modal-body">
                            <form action="{% url 'myapp:EcommerceBanner' %}" method="post"
                                  enctype="multipart/form-data">{% csrf_token %}
                                <input type="number" name="pid" value="{{i.id}}" hidden>
                                <input type="number" name="pcode" value="1" hidden>
                                <input type="file" name="photo1">
                                
                                <input type="submit" value="SavePhoto" class="btn btn-sm btn-info">
                            </form>
                        </div>

                    </div>

                </div>
            </div>
        </li>
        <li class="col-lg-4 col-md-6 col-sm-12">

            <div class="da-card box-shadow">
                <div class="da-card-photo">
                    <img src="{{i.photo2.url}}" alt=""/>
                    <div class="da-overlay">
                        <div class="da-social">
                            <h5 class="mb-10 color-white pd-20">
                                1904x600
                            </h5>
                            <ul class="clearfix">

                                <li></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <button type="button" class="btn btn-info btn-sm" data-toggle="modal" data-target="#myModal2">edit</button>
            <div class="modal fade" id="myModal2" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>

                        </div>
                        <div class="modal-body">
                            <form action="{% url 'myapp:EcommerceBanner' %}" method="post"
                                  enctype="multipart/form-data">{% csrf_token %}
                                <input type="number" name="pid" value="{{i.id}}" hidden>
                                <input type="number" name="pcode" value="2" hidden>
                                <input type="file" name="photo2">
                                
                                <input type="submit" value="SavePhoto" class="btn btn-sm btn-info">
                            </form>
                        </div>

                    </div>

                </div>
            </div>
            

        </li>

    </ul>


    
    {% endfor %}
</div>

{% endblock content %}

pos/templates/web/cart.html
{% extends 'web/webbase.html' %}
{% block content %}


<!--Page Title-->
<div class="page section-header text-center">
    <div class="page-title">
        <div class="wrapper"><h1 class="page-width">Your cart</h1></div>
      </div>
</div>
<!--End Page Title-->

<div class="container">
    <div class="row">
        <div class="col-12 col-sm-12 col-md-8 col-lg-8 main-col">
            <form action="#" method="post" class="cart style2">
                <table>
                    <thead class="cart__row cart__header">
                        <tr>
                            <th colspan="2" class="text-center">Product</th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-right">Total</th>
                            <th class="action">&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                        {% for p in cart.ecommercecartproduct_set.all %}
                        <tr class="cart__row border-bottom line1 cart-flex border-top">
                            <td class="cart__image-wrapper cart-flex-item">
                                <a href="#"><img class="cart__image" src="{{p.product.photo.url}}" alt="cart photo"></a>
                            </td>
                            <td class="cart__meta small--text-left cart-flex-item">
                                <div class="list-view-item__title">
                                    <a href="#">{{p.product.item_name}}({{p.item_color}} / {{p.item_size}})</a>
                                </div>
                            </td>
                            <td class="cart__price-wrapper cart-flex-item">
                                <span class="money">{{p.rate}}</span>
                            </td>
                            <td class="cart__update-wrapper cart-flex-item text-right">
                                <div class="cart__qty text-center">
                                    <div class="qtyField">
                                        <a class="qtyBtn minus" href="{% url 'myapp:WebCartManage' p.id %}?action=dcr"><i class="icon icon-minus"></i></a>
                                        <input class="cart__qty-input qty" type="text" name="updates[]" id="qty" value="{{p.quantity}}" pattern="[0-9]*">
                                        <a class="qtyBtn plus" href="{% url 'myapp:WebCartManage' p.id %}?action=inc"><i class="icon icon-plus"></i></a>
                                    </div>
                                </div>
                            </td>
                            <td class="text-right small--hide cart-price">
                                <div><span class="money">{{p.subtotal}}</span></div>
                            </td>
                            <td class="text-center small--hide"><a href="{% url 'myapp:WebCartManage' p.id %}?action=rmv" class="btn btn--secondary cart__remove" title="Remove tem"><i class="icon icon anm anm-times-l"></i></a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="3" class="text-left"><a href="/" class="btn--link cart-continue"><i class="icon icon-arrow-circle-left"></i> Continue shopping</a></td>
                            <td colspan="3" class="text-right"><a href="{% url 'myapp:WebCheckOut' %}" class="btn--link cart-update"><i class="fa fa-refresh"></i> Checkout</a></td>
                            <!-- <td colspan="3" class="text-right"><button type="submit" name="update" class="btn--link cart-update"><i class="fa fa-refresh"></i> Update</button></td> -->
                            
                        </tr>
                    </tfoot>
            </table>
            
            <div class="currencymsg">ဝယ်ယူအားပေးမှုအတွက် လူကြီးမင်းကို အထူးကျေးဇူးတင်ပါသည်။</div>
            <hr>
            <div id="shipping-calculator" class="mb-4">
                <h5 class="small--text-center"></h5>
                
            </div> 
            
            </form>                   
           </div>
        <!-- <div class="col-12 col-sm-12 col-md-4 col-lg-4 cart__footer">
            <div class="cart-note">
                <div class="solid-border">
                    <h5><label for="CartSpecialInstructions" class="cart-note__label small--text-center">ပို့ဆောင်ရမည့် လိပ်စာအချက်အလက်ဖြည့်ပါ</label></h5>
                    <textarea name="note" id="CartSpecialInstructions" class="cart-note__input"></textarea>
                </div>
            </div>
            <div class="solid-border">
              <div class="row">
                  <span class="col-12 col-sm-6 cart__subtotal-title"><strong>Subtotal</strong></span>
                <span class="col-12 col-sm-6 cart__subtotal-title cart__subtotal text-right"><span class="money">{{cart.super_total}}</span></span>
              </div>
              <div class="cart__shipping">Thank You !</div>
              
              <input type="submit" name="checkout" id="cartCheckout" class="btn btn--small-wide checkout" value="Checkout" disabled="disabled">
              
            </div>

        </div> -->
    </div>
</div>

</div>
<!--End Body Content-->





{% endblock content %}